// This file is automatically generated by generate_scriptable_factory.py from CMake

#pragma once
#include "../Core/Common/ecs/components/ntshengn_ecs_scriptable.h"
#include "../Core/scripting/ntshengn_script_keeper.h"
#include <string>

#include "camerascript.h"

namespace NtshEngn {

	namespace ScriptableFactory {

		Scriptable createScriptable(ScriptKeeper* scriptKeeper, const std::string& scriptName) {
			Scriptable scriptable;

			if (scriptName == "CameraScript") { scriptable.script = scriptKeeper->createScript<CameraScript>(); }

			return scriptable;
		}

	}

}