// This file is automatically generated by generate_script_manager.py from CMake

#include "ntshengn_script_manager.h"

#include "../CameraScript.h"

NtshEngn::Scriptable NtshEngn::ScriptManager::createScriptable(const std::string& scriptName) {
	Scriptable scriptable;

	if (scriptName == "CameraScript") {
		CameraScript* script = createScript<CameraScript>();
		script->createEditableScriptVariableMap();
		scriptable.script = script;
	}

	return scriptable;
}

void CameraScript::createEditableScriptVariableMap() {
}

extern "C" NTSHENGN_SCRIPT_MANAGER_API NtshEngn::ScriptManagerInterface* createScriptManager() {
	return new NtshEngn::ScriptManager;
}

extern "C" NTSHENGN_SCRIPT_MANAGER_API void destroyScriptManager(NtshEngn::ScriptManagerInterface* sm) {
	delete sm;
}